
package com.aw.services.controller;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.aw.services.repository.*;
import com.aw.services.model.*;

@Controller    // This means that this class is a Controller
@CrossOrigin
@RequestMapping(path="/click") // This means URL's start with /demo (after Application path)
public class QuestionClickController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private QuestionClickActivityRepository repo;
	
	@Autowired 
	private UserRepository userRepository;
	

	@GetMapping(path="/question") // Map ONLY GET Requests
	public @ResponseBody String addNewQClick (@RequestParam String userId, @RequestParam String questionString) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		
		System.out.println("hitting api ");

		QuestionClickActivity n = new QuestionClickActivity();
		n.setQuestion(questionString);
		User u = userRepository.findUser(userId);
		n.setUser(u);
		repo.save(n);
		return "Saved";
	}
	
	@GetMapping(path="/tag") // Map ONLY GET Requests
	public @ResponseBody String addNewtagClick (@RequestParam String userId, @RequestParam String tagString) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		
		System.out.println("hitting api ");

		QuestionClickActivity n = new QuestionClickActivity();
		n.setQuestion(tagString);
		User u = userRepository.findUser(userId);
		n.setUser(u);
		repo.save(n);
		return "Saved";
	}


	@GetMapping(path="/allQ")
	public @ResponseBody Iterable<QuestionClickActivity> getAllClicks() {
		// This returns a JSON or XML with the users
		return repo.findAll();
	}
	
	@GetMapping(path="/question/all")
	public @ResponseBody Iterable<QuestionClickActivity> getAllClicks(@RequestParam int userId) {
		// This returns a JSON or XML with the users
		return repo.findAllUserQClickActivity(userId);
	}
}